import { NextResponse } from 'next/server'

const provinces = [
  { name: 'Metro Manila', municipalities: ['Manila', 'Quezon City', 'Makati', 'Pasig', 'Taguig', 'Pasay', 'Caloocan', 'Malabon', 'Navotas', 'Valenzuela', 'Marikina', 'Muntinlupa', 'Las Piñas', 'Parañaque', 'Pateros', 'San Juan', 'Mandaluyong'] },
  { name: 'Cavite', municipalities: ['Bacoor', 'Imus', 'Dasmariñas', 'Tagaytay', 'Cavite City', 'General Trias', 'Trece Martires', 'Silang', 'Carmona', 'General Mariano Alvarez'] },
  { name: 'Laguna', municipalities: ['Santa Cruz', 'Calamba', 'San Pablo', 'Biñan', 'Los Baños', 'San Pedro', 'Sta. Rosa', 'Cabuyao', 'Pagsanjan', 'Bay'] },
  { name: 'Bulacan', municipalities: ['Malolos', 'Meycauayan', 'San Jose del Monte', 'Baliuag', 'Santa Maria', 'Marilao', 'Bocaue', 'Pulilan', 'Calumpit', 'Guiguinto'] },
  { name: 'Rizal', municipalities: ['Antipolo', 'Taytay', 'Angono', 'Cainta', 'Binangonan', 'Cardona', 'Morong', 'Baras', 'Rodriguez', 'Tanay'] },
  { name: 'Cebu', municipalities: ['Cebu City', 'Lapu-Lapu', 'Mandaue', 'Carcar', 'Bogo', 'Danao', 'Talisay', 'Toledo', 'Naga', 'Minglanilla'] },
  { name: 'Davao del Sur', municipalities: ['Davao City', 'Digos', 'Mati', 'Panabo', 'Tagum', 'Samal', 'Santo Tomas', 'Hagonoy', 'Malita', 'Sta. Cruz'] },
  { name: 'Iloilo', municipalities: ['Iloilo City', 'Passi', 'Oton', 'Pavia', 'Santa Barbara', 'Cabatuan', 'Jaro', 'Molo', 'Leon', 'Tigbauan'] },
  { name: 'Pampanga', municipalities: ['San Fernando', 'Angeles', 'Mabalacat', 'Apalit', 'Lubao', 'Porac', 'Guagua', 'Macabebe', 'Magalang', 'Mexico'] },
  { name: 'Batangas', municipalities: ['Batangas City', 'Lipa', 'Tanauan', 'Bauan', 'Santo Tomas', 'Nasugbu', 'Balayan', 'Lemery', 'Rosario', 'San Jose'] },
]

const barangayData: Record<string, Record<string, string[]>> = {
  'Metro Manila': {
    Manila: [
      'Binondo', 'Ermita', 'Intramuros', 'Malate', 'Paco', 'Pandacan', 'Port Area',
      'Quiapo', 'Sampaloc', 'San Andres', 'San Miguel', 'San Nicolas', 'Santa Ana',
      'Santa Cruz', 'Santa Mesa', 'Tondo',
    ],
    'Quezon City': [
      'Alicia', 'Bagbag', 'Bagong Lipunan ng Crame', 'Bagong Pag-asa', 'Bagong Silangan',
      'Bagumbayan', 'Bagumbuhay', 'Bahay Toro', 'Batasan Hills', 'Betterliving',
      'Claro', 'Commonwealth', 'Culiat', 'Diliman', 'Duyan-Duyan',
      'Holy Spirit', 'Kaligayahan', 'Kalusugan', 'Kamuning', 'Katipunan',
      'Krus na Ligas', 'Loyola Heights', 'Malaya', 'Manresa', 'Matandang Balara',
      'New Era', 'Novaliches Proper', 'Pag-ibig sa Nayon', 'Pasong Putik Proper',
      'Phil-Am', 'Project 4', 'Project 6', 'Project 7', 'Project 8',
      'Quirino 2-A', 'Roxas', 'San Agustin', 'San Bartolome', 'San Isidro Labrador',
      'Sangandaan', 'Santo Cristo', 'Sauyo', 'Sienna', 'Talipapa',
      'Tandang Sora', 'Ugong Norte', 'Unang Sigaw', 'Valencia',
    ],
    Makati: [
      'Bangkal', 'Bel-Air', 'Carmona', 'Cembo', 'Comembo', 'Dasmariñas',
      'East Rembo', 'Forbes Park', 'Guadalupe Nuevo', 'Guadalupe Viejo',
      'Kasilawan', 'La Paz', 'Magallanes', 'Olympia', 'Palanan',
      'Pembo', 'Pinagkaisahan', 'Pio del Pilar', 'Pitogo', 'Poblacion',
      'Post Proper Northside', 'Post Proper Southside', 'Rizal', 'San Antonio',
      'San Isidro', 'San Lorenzo', 'Santa Cruz', 'Singkamas', 'South Cembo',
      'Tejeros', 'Urdaneta', 'Valenzuela', 'West Rembo',
    ],
    Pasig: [
      'Bagong Ilog', 'Bagong Katipunan', 'Bambang', 'Buting', 'Caniogan',
      'Dela Paz', 'Kalawaan', 'Kapasigan', 'Kapitolyo', 'Malinao',
      'Manggahan', 'Maybunga', 'Oranbo', 'Palatiw', 'Pinagbuhatan',
      'Pineda', 'Rosario', 'Sagad', 'San Antonio', 'San Joaquin',
      'San Jose', 'San Miguel', 'San Nicolas', 'Santa Cruz', 'Santa Lucia',
      'Santa Rosa', 'Santo Tomas', 'Sumilang', 'Ugong',
    ],
    Taguig: [
      'Bagumbayan', 'Bambang', 'Calzada', 'Central Bicutan', 'Central Signal Village',
      'Fort Bonifacio', 'Hagonoy', 'Ibayo-Tipas', 'Katuparan', 'Ligid-Tipas',
      'Lower Bicutan', 'Maharlika Village', 'Napindan', 'New Lower Bicutan',
      'North Daang Hari', 'North Signal Village', 'Palingon', 'Pembo',
      'Pinagsama', 'San Miguel', 'Santa Ana', 'South Daang Hari',
      'South Signal Village', 'Tanyag', 'Tuktukan', 'Upper Bicutan',
      'Ususan', 'Wawa', 'Western Bicutan',
    ],
    Pasay: [
      'Bagong Pugad', 'Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4',
      'Barangay 5', 'Barangay 6', 'Barangay 7', 'Barangay 8', 'Barangay 9',
      'Barangay 10', 'Barangay 11', 'Barangay 12', 'Barangay 13', 'Barangay 14',
      'Barangay 15', 'Barangay 16', 'Barangay 17', 'Barangay 18', 'Barangay 19',
      'Barangay 20', 'Barangay 21', 'Barangay 22', 'Barangay 23', 'Barangay 24',
      'Don Bosco', 'Malibay', 'Maricaban', 'Nichols', 'San Isidro',
      'San Jose', 'San Raphael', 'Santo Niño', 'Villamor',
    ],
    Caloocan: [
      'Bagong Silang', 'Barangay 1', 'Barangay 5', 'Barangay 14', 'Barangay 15',
      'Barangay 16', 'Barangay 17', 'Barangay 18', 'Barangay 19', 'Barangay 20',
      'Camarin', 'Deparo', 'Llano', 'Malaria', 'Maypajo',
      'Novaliches', 'Pangarap', 'Pag-asa', 'Sangandaan', 'Tala',
    ],
    Malabon: [
      'Acacia', 'Baritan', 'Bayan-Bayanan', 'Catmon', 'Concepcion',
      'Dampalit', 'Flores', 'Hulong Duhat', 'Ibaba', 'Longos',
      'Maysilo', 'Muzon', 'Niugan', 'Panghulo', 'Poblacion',
      'Potrero', 'San Agustin', 'Santolan', 'Tinajeros', 'Tonsuya',
    ],
    Navotas: [
      'Bagumbayan North', 'Bagumbayan South', 'Bangculasi', 'Daanghari',
      'Navotas East', 'Navotas West', 'North Bay Blvd North', 'North Bay Blvd South',
      'San Jose', 'San Roque', 'Sipac-Almacen', 'Tangos North', 'Tangos South',
    ],
    Valenzuela: [
      'Arkong Bato', 'Bagbaguin', 'Balangkas', 'Bignay', 'Bisig',
      'Canumay East', 'Canumay West', 'Coloong', 'Dalandanan', 'Gen. T. de Leon',
      'Isla', 'Karuhatan', 'Lawang Bato', 'Lingunan', 'Mabolo',
      'Malanday', 'Malinta', 'Mapulang Lupa', 'Marulas', 'Maysan',
      'Palasan', 'Parada', 'Pariancillo Villa', 'Pasolo', 'Poblacion',
      'Pulo', 'Punturin', 'Rincon', 'Tagalag', 'Ugong',
      'Viente Reales', 'Wawang Pulo',
    ],
    Marikina: [
      'Barangka', 'Calumpang', 'Concepcion Dos', 'Concepcion Uno',
      'Fortune', 'Industrial Valley', 'Jesus dela Peña', 'Malanday',
      'Marikina Heights', 'Nangka', 'Parang', 'San Roque',
      'Santa Elena', 'Santo Niño', 'Tañong', 'Tumana',
    ],
    Muntinlupa: [
      'Alabang', 'Ayala Alabang', 'Bayanan', 'Buli', 'Cupang',
      'Poblacion', 'Putatan', 'Sucat', 'Tunasan',
    ],
    'Las Piñas': [
      'Almanza Dos', 'Almanza Uno', 'BF Resort', 'Daniel Fajardo',
      'Elias Aldana', 'Ilaya', 'Manuyo Dos', 'Manuyo Uno',
      'Pamplona Dos', 'Pamplona Tres', 'Pamplona Uno',
      'Pilar', 'Pulang Lupa Dos', 'Pulang Lupa Uno',
      'Talon Dos', 'Talon Kuatro', 'Talon Singko', 'Talon Tres', 'Talon Uno',
      'Zapote',
    ],
    Parañaque: [
      'Baclaran', 'BF Homes', 'Don Bosco', 'Don Galo', 'La Huerta',
      'Marcelo Green', 'Merville', 'Moonwalk', 'San Dionisio',
      'San Isidro', 'San Martin de Porres', 'Santo Niño',
      'Sun Valley', 'Tambo', 'Vitalez',
    ],
    Pateros: [
      'Aguho', 'Magtanggol', 'Maharlika', 'Poblacion', 'San Pedro',
      'San Roque', 'Santa Ana', 'Santo Rosario-Kanluran', 'Santo Rosario-Silangan', 'Tabacalera',
    ],
    'San Juan': [
      'Balong Bato', 'Batis', 'Corazon de Jesus', 'Ermitaño', 'Greenhills',
      'Isabelita', 'Kabayanan', 'Little Baguio', 'Maytunas', 'Onse',
      'Pasadeña', 'Pedro Cruz', 'Progreso', 'Rivera', 'Salapan',
      'San Perfecto', 'Santa Lucia', 'Tibagan', 'West Crame',
    ],
    Mandaluyong: [
      'Addition Hills', 'Bagong Silang', 'Barangka Drive', 'Barangka Ibaba',
      'Barangka Ilaya', 'Barangka Itaas', 'Buayang Bato', 'Burol',
      'Daang Bakal', 'Hagdan Bato Itaas', 'Hagdan Bato Libis',
      'Harapin Ang Bukas', 'Highway Hills', 'Hulo', 'Ilaya',
      'Mabini-J. Rizal', 'Malamig', 'Mauway', 'Namayan',
      'New Zañiga', 'Old Zañiga', 'Pag-asa', 'Plainview',
      'Pleasant Hills', 'Poblacion', 'San Jose', 'Vergara',
      'Wack-Wack Greenhills',
    ],
  },
  Cavite: {
    Bacoor: [
      'Alima', 'Aniban I', 'Aniban II', 'Aniban III', 'Aniban IV', 'Aniban V',
      'Banalo', 'Bayanan', 'Campo Santo', 'Daang Bukid', 'Digman',
      'Dulong Bayan', 'Habay I', 'Habay II', 'Kaingin', 'Ligas I',
      'Ligas II', 'Ligas III', 'Mambog I', 'Mambog II', 'Mambog III',
      'Mambog IV', 'Mambog V', 'Molino I', 'Molino II', 'Molino III',
      'Molino IV', 'Molino V', 'Molino VI', 'Molino VII',
      'Niog I', 'Niog II', 'Niog III', 'Panapaan I', 'Panapaan II',
      'Panapaan III', 'Panapaan IV', 'Panapaan V', 'Panapaan VI',
      'Panapaan VII', 'Panapaan VIII', 'Real I', 'Real II',
      'Salinas I', 'Salinas II', 'Salinas III', 'Salinas IV',
      'San Nicolas I', 'San Nicolas II', 'San Nicolas III',
      'Sineguelasan', 'Tabing Dagat', 'Talaba I', 'Talaba II',
      'Talaba III', 'Talaba IV', 'Talaba V', 'Talaba VI', 'Talaba VII',
      'Zapote I', 'Zapote II', 'Zapote III', 'Zapote IV', 'Zapote V',
    ],
    Imus: [
      'Alapan I-A', 'Alapan I-B', 'Alapan I-C', 'Alapan II-A', 'Alapan II-B',
      'Anabu I-A', 'Anabu I-B', 'Anabu I-C', 'Anabu I-D', 'Anabu I-E',
      'Anabu I-F', 'Anabu I-G', 'Anabu II-A', 'Anabu II-B', 'Anabu II-C',
      'Anabu II-D', 'Anabu II-E', 'Anabu II-F', 'Bayan Luma I',
      'Bayan Luma II', 'Bayan Luma III', 'Bayan Luma IV', 'Bayan Luma V',
      'Bayan Luma VI', 'Bayan Luma VII', 'Bayan Luma VIII', 'Bayan Luma IX',
      'Bucandala I', 'Bucandala II', 'Bucandala III', 'Bucandala IV', 'Bucandala V',
      'Carsadang Bago I', 'Carsadang Bago II', 'Magdalo', 'Maharlika',
      'Malagasang I-A', 'Malagasang I-B', 'Malagasang I-C', 'Malagasang I-D',
      'Malagasang I-E', 'Malagasang I-F', 'Malagasang I-G',
      'Malagasang II-A', 'Malagasang II-B', 'Malagasang II-C',
      'Malagasang II-D', 'Malagasang II-E', 'Malagasang II-F', 'Malagasang II-G',
      'Medicion I-A', 'Medicion I-B', 'Medicion I-C', 'Medicion I-D',
      'Medicion II-A', 'Medicion II-B', 'Medicion II-C', 'Medicion II-D',
      'Medicion II-E', 'Medicion II-F', 'Pag-asa I', 'Pag-asa II', 'Pag-asa III',
      'Palico I', 'Palico II', 'Palico III', 'Palico IV',
      'Pasong Buaya I', 'Pasong Buaya II', 'Pinagbuklod', 'Poblacion I-A',
      'Poblacion I-B', 'Poblacion I-C', 'Poblacion II-A', 'Poblacion II-B',
      'Poblacion III-A', 'Poblacion III-B', 'Poblacion IV-A', 'Poblacion IV-B',
      'Tanzang Luma I', 'Tanzang Luma II', 'Tanzang Luma III',
      'Tanzang Luma IV', 'Tanzang Luma V', 'Tanzang Luma VI',
      'Tinik', 'Toclong I-A', 'Toclong I-B', 'Toclong I-C', 'Toclong II-A', 'Toclong II-B',
    ],
    Dasmariñas: [
      'Burol I', 'Burol II', 'Burol III', 'Datu Esmael', 'Emmanuel Bergado I',
      'Emmanuel Bergado II', 'Fatima I', 'Fatima II', 'Fatima III',
      'Habay', 'Langkaan I', 'Langkaan II', 'Luzviminda I', 'Luzviminda II',
      'Magurhon', 'Mehan', 'Paliparan I', 'Paliparan II', 'Paliparan III',
      'Sabang', 'Salawag', 'Salitran I', 'Salitran II', 'Salitran III', 'Salitran IV',
      'Sampaloc I', 'Sampaloc II', 'Sampaloc III', 'Sampaloc IV', 'Sampaloc V',
      'San Agustin I', 'San Agustin II', 'San Agustin III',
      'San Andres I', 'San Andres II', 'San Jose', 'San Miguel I',
      'San Miguel II', 'San Simon', 'Santa Cristina I', 'Santa Cristina II',
      'Santa Cruz I', 'Santa Cruz II', 'Santa Lucia', 'Santa Maria',
      'Santiago', 'Santo Cristo', 'Santo Niño I', 'Santo Niño II',
      'Tejero', 'Victoria Reyes',
    ],
    Tagaytay: [
      'Asisan', 'Bagong Tubig', 'Calabuso', 'Cале', 'Francisco', 'Guinhawa North',
      'Guinhawa South', 'Iruhin East', 'Iruhin South', 'Iruhin West',
      'Kaybagal East', 'Kaybagal North', 'Kaybagal South', 'Mag-asawang Ilat',
      'Maharlika East', 'Maharlika West', 'Maitim 2nd East', 'Maitim 2nd Central',
      'Maitim 2nd West', 'Mendez Crossing East', 'Mendez Crossing West',
      'Neogan', 'Patutong Malaki North', 'Patutong Malaki South',
      'Poblacion', 'San Jose', 'Silang Junction North', 'Silang Junction South',
      'Sungay East', 'Sungay West', 'Tolentino East', 'Tolentino West',
      'Zambal',
    ],
    'Cavite City': [
      'Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4', 'Barangay 5',
      'Barangay 6', 'Barangay 7', 'Barangay 8', 'Barangay 9', 'Barangay 10',
      'Barangay 11', 'Barangay 12', 'Barangay 13', 'Barangay 14', 'Barangay 15',
      'Barangay 16', 'Barangay 17', 'Barangay 18', 'Barangay 19', 'Barangay 20',
      'Barangay 21', 'Barangay 22', 'Barangay 23', 'Barangay 24',
    ],
    'General Trias': [
      'Alingaro', 'Arnaldo', 'Bacao I', 'Bacao II', 'Bagumbayan',
      'Biclatan', 'Buenavista I', 'Buenavista II', 'Buenavista III',
      'Corregidor', 'Dulong Bayan', 'Gov. Ferrer', 'Javalera',
      'Lapidario', 'Ligtong I', 'Ligtong II', 'Ligtong III', 'Ligtong IV',
      'Luciano', 'Manggahan', 'Navarro', 'Panungyanan', 'Pasong Camachile I',
      'Pasong Camachile II', 'Pasong Kawayan I', 'Pasong Kawayan II',
      'Pinagtipunan', 'Poblacion I', 'Poblacion II', 'Poblacion III',
      'San Francisco', 'San Gabriel', 'San Juan I', 'San Juan II',
      'Santiago', 'Santulan', 'Tejero', 'Vibora', 'Vigan',
    ],
    'Trece Martires': [
      'Aguado', 'Cabezas', 'Cabuco', 'De Ocampo', 'Gregorio',
      'Inocencio', 'Lallana', 'Lapidario', 'Luciano', 'Osorio',
      'Perez', 'Poblacion I', 'Poblacion II', 'Poblacion III',
      'Poblacion IV', 'Poblacion V', 'Poblacion VI', 'Recanto', 'Riberal',
    ],
    Silang: [
      'Acacia', 'Adlas', 'Anahaw I', 'Anahaw II', 'Arnaldo',
      'Batas', 'Biga I', 'Biga II', 'Biluso', 'Buho',
      'Bulihan', 'Cabianca', 'Carmen', 'Hoyo', 'Hukay',
      'Inchican', 'Ipil', 'Iring-Iring', 'Kaong', 'Lalaan I',
      'Lalaan II', 'Ligtong I', 'Ligtong II', 'Litlit', 'Lucsuhin',
      'Lumil', 'Maguyam', 'Malabag', 'Mataas na Lupa', 'Naic',
      'Paciano Rizal', 'Pag-asa', 'Paliparan', 'Pasong Langka',
      'Pooc I', 'Pooc II', 'Pulong Bunga', 'Pulong Santa Cruz',
      'Puting Kahoy', 'Sabutan', 'San Miguel I', 'San Miguel II',
      'San Vicente I', 'San Vicente II', 'Santa Rosa I', 'Santa Rosa II',
      'Santo Niño', 'Tartaria', 'Tibig', 'Tubigan',
    ],
    Carmona: [
      'Bancal', 'Cabilang Baybay', 'General Pio', 'Lantic',
      'Mabuhay', 'Maduya', 'Miong', 'Poblacion', 'Salikin',
      'Sulucan', 'Talipain',
    ],
    'General Mariano Alvarez': [
      'Aldiano Olaes', 'Barangay I', 'Barangay II', 'Barangay III',
      'Barangay IV', 'Barangay V', 'Barangay VI', 'Barangay VII',
      'Barangay VIII', 'Barangay IX', 'Barangay X', 'Barangay XI',
      'Barangay XII', 'Barangay XIII', 'Barangay XIV', 'Barangay XV',
      'Barangay XVI', 'Barangay XVII',
    ],
  },

  Laguna: {
    'Santa Cruz': [
      'Bagong Silang', 'Bagumbayan', 'Balayhangin', 'Banlic', 'Barangay I',
      'Barangay II', 'Barangay III', 'Barangay IV', 'Barangay V', 'Barangay VI',
      'Bubuyan', 'Bukal', 'Bungkol', 'Buo', 'Burlungan',
      'Gatid', 'Kulapi', 'Lupi', 'Malabanban Norte', 'Malabanban Sur',
      'Malinao', 'Mangga', 'Masico', 'Nagcarlan', 'Oogong',
      'Paluan', 'Pasong', 'Patimbao', 'Poblacion I', 'Poblacion II',
      'Salasad', 'San Pablo Norte', 'San Pablo Sur', 'Santisima Cruz',
      'Santo Angel Norte', 'Santo Angel Sur', 'Sisilmin', 'Tabak',
      'Tuklas', 'Wawa',
    ],
    Calamba: [
      'Bagong Kalsada', 'Banadero', 'Banlic', 'Barandal', 'Batino',
      'Bubuyan', 'Bucal', 'Burol', 'Camaligan', 'Canlubang',
      'Halang', 'Hornalan', 'Kay-anlog', 'La Mesa', 'Laguerta',
      'Lawa', 'Lecheria', 'Looc', 'Mabato', 'Majada Labas',
      'Majada Out', 'Makiling', 'Mapagong', 'Masili', 'Maunong',
      'Mayapa', 'Milagrosa', 'Paciano Rizal', 'Palingon', 'Palo Alto',
      'Pansol', 'Parian', 'Prinza', 'Punta', 'Putho Tuntungin',
      'Real', 'Saimsim', 'Sampiruhan', 'San Cristobal', 'San Jose',
      'San Juan', 'Sirang Lupa', 'Sucol', 'Turbina', 'Ulango',
      'Uwisan',
    ],
    'San Pablo': [
      'Bagong Bayan II-A', 'Bagong Pook VI-C', 'Barangay I', 'Barangay II',
      'Barangay III', 'Barangay IV', 'Barangay V', 'Barangay VI',
      'Barangay VII', 'Concepcion', 'Del Remedio', 'Dolores',
      'San Buenaventura', 'San Francisco', 'San Gabriel', 'San Ignacio',
      'San Jose', 'San Juan', 'San Lucas I', 'San Lucas II',
      'San Marcos', 'San Mateo', 'San Miguel', 'San Nicolas',
      'San Pedro', 'San Rafael', 'San Roque', 'San Vicente',
      'Santa Barbara', 'Santa Catalina', 'Santa Cruz', 'Santa Filomena',
      'Santa Maria', 'Santa Veronica', 'Santo Angel', 'Santo Cristo',
      'Santo Niño', 'Soledad',
    ],
    Biñan: [
      'Biñan', 'Bungahan', 'Canlalay', 'Casile', 'De La Paz',
      'Ganado', 'Langkiwa', 'Loma', 'Malaban', 'Malamig',
      'Mampalasan', 'Platero', 'Poblacion', 'San Antonio',
      'San Francisco', 'San Jose', 'San Vicente', 'Santo Domingo',
      'Santo Tomas', 'Soro-soro', 'Santo Niño', 'Timbao', 'Tubigan', 'Zapote',
    ],
    'Los Baños': [
      'Anos', 'Bagong Silang', 'Bambang', 'Batong Malake', 'Bayog',
      'Calo', 'Caridad', 'Lalakay', 'Maahas', 'Malinta',
      'Mayondon', 'Putho Tuntungin', 'San Antonio', 'Tadlak',
      'Timugan',
    ],
    'San Pedro': [
      'Bagong Silang', 'Calendola', 'Chrysanthemum', 'Cuyab', 'Estrella',
      'Fatima', 'G.S.I.S.', 'Landayan', 'Langgam', 'Laram',
      'Magsaysay', 'Maharlika', 'Narra', 'Nueva', 'Pacita I',
      'Pacita II', 'Poblacion', 'Riverside', 'Sampaguita',
      'San Antonio', 'San Lorenzo Ruiz', 'San Roque', 'San Vicente',
      'Santo Niño', 'United Bayanihan', 'United Better Living',
    ],
    'Sta. Rosa': [
      'Aplaya', 'Balibago', 'Caingin', 'Dila', 'Dita',
      'Don Jose', 'Ibaba', 'Kanluran', 'Labas', 'Macabling',
      'Malitlit', 'Malusak', 'Market Area', 'Pook', 'Pulong Santa Cruz',
      'Santo Domingo', 'Sinalhan', 'Tagapo',
    ],
    Cabuyao: [
      'Baclaran', 'Banay-banay', 'Banlic', 'Bigaa', 'Butong',
      'Casile', 'Diezmo', 'Gulod', 'Mamatid', 'Marinig',
      'Niugan', 'Pittland', 'Pulo', 'Sala', 'San Isidro',
      'Sucol',
    ],
    Pagsanjan: [
      'Anibong', 'Baleco', 'Baliang', 'Buboy', 'Calusiche',
      'Dingin', 'Lambac', 'Layugan', 'Magdapio', 'Mahagaya',
      'Pag-asa', 'Pinagsanjan', 'Poblacion I', 'Poblacion II',
      'Sabang', 'San Isidro', 'Sambal', 'Tagumpay', 'Tibatib',
    ],
    Bay: [
      'Bitin', 'Calo', 'Dila', 'Maitim', 'Masaya',
      'Puypuy', 'San Agustin', 'Tadlak',
    ],
  },
  Bulacan: {
    Malolos: [
      'Anilao', 'Atlag', 'Babatnin', 'Bagna', 'Bagong Bayan',
      'Balayong', 'Balite', 'Bangkal', 'Barihan', 'Bulihan',
      'Bungahan', 'Caingin', 'Calero', 'Calizon', 'Calumpang',
      'Camachilihan', 'Camias', 'Caniogan', 'Catmon', 'Cofradia',
      'Dakila', 'Guinhawa', 'Ligas', 'Liyang', 'Longos',
      'Look 1st', 'Look 2nd', 'Lugam', 'Mabolo', 'Mambog',
      'Masile', 'Matimbo', 'Mojon', 'Namayan', 'Niugan',
      'Pamarawan', 'Panasahan', 'Pinagbakahan', 'San Agustin',
      'San Gabriel', 'San Juan', 'San Pablo', 'San Vicente',
      'Santiago', 'Santisima Trinidad', 'Santo Rosario', 'Santol',
      'Sumapang Bata', 'Sumapang Matanda', 'Taal', 'Tikay',
    ],
    Meycauayan: [
      'Bagbaguin', 'Bahay Pare', 'Bangkal', 'Banga', 'Bayugo',
      'Caingin', 'Caloocan', 'Camalig', 'Gasak', 'Hulo',
      'Iba', 'Langka', 'Lawa', 'Libtong', 'Liputan',
      'Longos', 'Malhacan', 'Pajo', 'Pandayan', 'Pantoc',
      'Perez', 'Poblacion', 'Saluysoy', 'San Francisco',
      'San Jose Patag', 'Santa Maria', 'Turo', 'Tugatog', 'Ubog', 'Yantok',
    ],
    'San Jose del Monte': [
      'Assumption', 'Bagong Buhay I', 'Bagong Buhay II', 'Bagong Buhay III',
      'Citrus', 'Ciudad Real', 'Dulong Bayan', 'Fatima I', 'Fatima II',
      'Fatima III', 'Fatima IV', 'Fatima V', 'Francisco Homes-Guijo',
      'Francisco Homes-Mulawin', 'Francisco Homes-Narra', 'Francisco Homes-Yakal',
      'Graceville', 'Gumaok Central', 'Gumaok East', 'Gumaok West',
      'Kaybanban', 'Kaypian', 'Lawang Pari', 'Maharlika', 'Minuyan I',
      'Minuyan II', 'Minuyan III', 'Minuyan IV', 'Minuyan V',
      'Minuyan Proper', 'Mulawin', 'Paradise III', 'Poblacion',
      'Poblacion I', 'Poblacion II', 'Poblacion III',
      'San Manuel', 'San Martin I', 'San Martin II', 'San Martin III',
      'San Martin IV', 'San Pedro', 'San Rafael I', 'San Rafael II',
      'San Rafael III', 'San Rafael IV', 'Santa Cruz I', 'Santa Cruz II',
      'Santa Cruz III', 'Santa Cruz IV', 'Santa Cruz V',
      'Santo Cristo I', 'Santo Cristo II', 'Sapang Palay Proper',
      'St. Martin de Porres', 'Tungkong Mangga',
    ],
    Baliuag: [
      'Bagong Nayon', 'Barangka', 'Calantipay', 'Catulinan',
      'Concepcion', 'Hinukay', 'Maламig', 'Pagala', 'Paitan',
      'Piel', 'Pinagbarilan', 'Poblacion', 'Sabang', 'San Jose',
      'San Roque', 'San Sebastian', 'Santa Barbara', 'Santa Cruz',
      'Santo Cristo', 'Santo Niño', 'Subic', 'Sulivan', 'Tangos', 'Tarcan',
      'Tiaong', 'Tibag', 'Tilapayong', 'Virgen delas Flores',
    ],
    'Santa Maria': [
      'Bagbaguin', 'Balasing', 'Buenavista', 'Bulac', 'Camangyanan',
      'Catcot', 'Concepcion', 'Guyong', 'Lalakhan', 'Mag-asawang Sapa',
      'Mahabang Parang', 'Manggahan', 'Parada', 'Pulong Yantok',
      'Salapungan', 'Sampaloc', 'San Jose', 'San Vicente', 'Santa Clara',
      'Santa Cruz', 'Silangan', 'Tabing Bakod', 'Tumana',
    ],
    Marilao: [
      'Abangan Norte', 'Abangan Sur', 'Bagbaguin', 'Balasing',
      'Bayan ng Marilao', 'Bungahan', 'Caingin', 'Cumba',
      'Ibayo', 'Lambakin', 'Lias', 'Loma de Gato',
      'Nagbalon', 'Patubig', 'Poblacion I', 'Poblacion II',
      'Pulong Buhangin', 'San Gabriel', 'San Jose', 'Santa Rosa',
      'Santo Niño', 'Saog', 'Tabing Ilog',
    ],
    Bocaue: [
      'Bagumbayan', 'Binagbag', 'Bunlo', 'Caingin', 'Duhat',
      'Igulot', 'Lolomboy', 'Poblacion', 'Sulucan', 'Tambobong',
      'Turo', 'Wakas',
    ],
    Pulilan: [
      'Balatong A', 'Balatong B', 'Cutcot', 'Dampol 1st',
      'Dampol 2nd A', 'Dampol 2nd B', 'Dulong Malapit', 'Inaon',
      'Longos', 'Lumbang', 'Paliwas', 'Paltok', 'Penabatan',
      'Poblacion', 'Santo Cristo', 'Taguig', 'Tibag', 'Tinejero',
    ],
    Calumpit: [
      'Balangkare Norte', 'Balangkare Sur', 'Balite', 'Bingahan',
      'Buguion', 'Bulusan', 'Calizon', 'Calumpang', 'Cambio',
      'Iba Este', 'Iba O Este', 'Longos', 'Meysulao', 'Meyto',
      'Palimbang', 'Panducot', 'Pit Guyod', 'San Marcos',
      'San Pedro', 'Santa Lucia', 'Santa Maria', 'Sapang Bayan',
      'Sucol', 'Tining',
    ],
    Guiguinto: [
      'Bulihan', 'Ilang-Ilang', 'Malis', 'Panginay', 'Plaridel',
      'Poblacion', 'Pritil', 'Pulong Yantok', 'Santa Cruz',
      'Santo Cristo', 'Tabang', 'Tiaong', 'Tukod',
    ],
  },
  Rizal: {
    Antipolo: [
      'Bagong Nayon', 'Beverly Hills', 'Calawis', 'Cupang', 'Dalig',
      'Dela Paz', 'Inarawan', 'Mambugan', 'Mayamot', 'Muyong',
      'San Isidro', 'San Jose', 'San Juan', 'San Luis', 'San Pedro',
      'San Roque', 'Santa Cruz', 'Santo Niño',
    ],
    Taytay: [
      'Dolores', 'Muzon', 'San Isidro', 'San Juan', 'Santa Ana',
    ],
    Angono: [
      'Bagumbayan', 'Kalayaan', 'Malinao', 'Mambog', 'Palma',
      'San Isidro', 'San Pedro', 'Santo Niño',
    ],
    Cainta: [
      'Banting', 'Brevaldo', 'Calaanan', 'San Andres', 'San Juan',
      'San Roque', 'Santa Rosa', 'Santo Domingo',
    ],
    Binangonan: [
      'Bangad', 'Batingan', 'Bilibiran', 'Binangonan', 'Calumpang',
      'Ithan', 'Janosa', 'Kasile', 'Kinagatan', 'Layunan',
      'Libid', 'Limbon', 'Macamot', 'Mambog', 'Opias',
      'Palangoy', 'Pantok', 'Pila Pila', 'Pipindan', 'San Carlos',
      'Tagpos', 'Tatala', 'Tinosa',
    ],
    Cardona: [
      'Balibago', 'Cardona', 'Dalig', 'Iglesia', 'Janosa',
      'Kaytome', 'Kinahatan', 'Libo', 'Malanggam-Catugas', 'Nagsulo',
      'Navotas', 'Real', 'Sampad', 'San Roque', 'Santa Rosa',
      'Sapa', 'Ticulio',
    ],
    Morong: [
      'Bombongan', 'Can-Cal-Lan', 'Lagundi', 'Maybancal',
      'Poblacion', 'San Guillermo', 'San Jose', 'San Juan',
      'San Pedro', 'Santa Catalina', 'Santo Niño', 'Wawa',
    ],
    Baras: [
      'Concepcion', 'Pinugay', 'San Jose', 'San Juan',
      'San Miguel', 'San Rafael',
    ],
    Rodriguez: [
      'Balite', 'Burgos', 'Geronimo', 'Macabud', 'Manggahan',
      'Mascap', 'Puray', 'Rosario', 'San Isidro', 'San Jose',
      'San Rafael',
    ],
    Tanay: [
      'Cayabu', 'Cuyambay', 'Daraitan', 'Katipunan', 'Laiban',
      'Mag-ampon', 'Mamuyao', 'Pinagkamaligan', 'Poblacion',
      'San Andres', 'San Isidro', 'San Juan', 'San Roque',
      'Santa Inez', 'Tabing Ilog', 'Tandang Kutyo', 'Wawa',
    ],
  },

  Cebu: {
    'Cebu City': [
      'Adlaon', 'Agsungot', 'Apas', 'Babag', 'Bacayan',
      'Banilad', 'Basak Pardo', 'Basak San Nicolas', 'Binaliw',
      'Bonbon', 'Budlaan', 'Bulacao', 'Buot-Taup Pardo', 'Busay',
      'Calamba', 'Cambinocot', 'Capitol Site', 'Carreta', 'Cogon Pardo',
      'Cogon Ramos', 'Day-as', 'Ermita', 'Guadalupe', 'Guba',
      'Hippodromo', 'Inayawan', 'Kalubihan', 'Kalunasan', 'Kamagayan',
      'Kasambagan', 'Kinasang-an Pardo', 'Labangon', 'Lahug',
      'Lorega San Miguel', 'Lusaran', 'Luz', 'Mabini', 'Mabolo',
      'Malubog', 'Mambaling', 'Pahina Central', 'Pahina San Nicolas',
      'Pamutan', 'Pardo', 'Pari-an', 'Paril', 'Pasil',
      'Pit-os', 'Poblacion Pardo', 'Pung-ol-Sibugay', 'Punta Princesa',
      'Putlod', 'Quiot Pardo', 'Sambag I', 'Sambag II',
      'San Antonio', 'San Jose', 'San Nicolas Central', 'San Nicolas Proper',
      'San Roque', 'Santa Cruz', 'Santo Niño', 'Sapangdaku',
      'Sinsin', 'Sirao', 'Suba Pasil', 'Sudlon I', 'Sudlon II',
      'T. Padilla', 'Tabunan', 'Tagbao', 'Taptap', 'Tejero',
      'Tinago', 'Tisa', 'To-ong Pardo', 'Toong', 'Zapatera',
    ],
    'Lapu-Lapu': [
      'Agus', 'Babag', 'Bankal', 'Baring', 'Basak',
      'Buaya', 'Calawisan', 'Canjulao', 'Caubian', 'Caw-oy',
      'Cawhagan', 'Gun-ob', 'Ibo', 'Looc', 'Mactan',
      'Maribago', 'Marigondon', 'Pajac', 'Pakna-an', 'Poblacion',
      'Punta Engaño', 'Pusok', 'Sabang', 'San Vicente', 'Santa Rosa',
      'Subabasbas', 'Talima', 'Tingo', 'Tungasan',
    ],
    Mandaue: [
      'Bakilid', 'Banilad', 'Basak', 'Cambaro', 'Canduman',
      'Casili', 'Casuntingan', 'Centro', 'Cubacub', 'Guizo',
      'Ibabao-Estancia', 'Jagobiao', 'Labogon', 'Looc',
      'Maguikay', 'Mantuyong', 'Opao', 'Pakna-an', 'Paknaan',
      'Subangdaku', 'Tabok', 'Tawason', 'Tingub', 'Tipolo', 'Umapad',
    ],
    Carcar: [
      'Bolinawan', 'Boljoon', 'Bonbon', 'Bulod', 'Bunga',
      'Cansaya', 'Cogon', 'Guadalupe', 'Liburon', 'Napo',
      'Ocaña', 'Perrelos', 'Poblacion I', 'Poblacion II',
      'Poblacion III', 'Tuyom', 'Valencia', 'Valladolid',
    ],
    Bogo: [
      'Anonang Norte', 'Anonang Sur', 'Banban', 'Binabag',
      'Bungtod', 'Carbon', 'Cayang', 'Cogon', 'Dakit',
      'Don Pedro Rodriguez', 'Gairan', 'Guadalupe', 'La Paz',
      'Lapaz', 'Lourdes', 'Malingin', 'Marangog', 'Nailon',
      'Odlot', 'Pandan Gitna', 'Pandan Weste', 'Poblacion Norte',
      'Poblacion Sur', 'Polambato', 'Sambag', 'San Vicente',
      'Santo Niño', 'Siocon', 'Sudlonon', 'Taytayan',
    ],
    Danao: [
      'Baliang', 'Bayabas', 'Binaliw', 'Bonotok', 'Cabungahan',
      'Cagat-Lamac', 'Cahumayan', 'Cambanay', 'Cambubho',
      'Cogon-Cruz', 'Danasan', 'Dungga', 'Dunggoan', 'Guinacot',
      'Guinsay', 'Ilihan Norte', 'Ilihan Sur', 'Langosig',
      'Lawaan', 'Licos', 'Looc', 'Magtagobtob', 'Malapoc Norte',
      'Manlayag', 'Masaba', 'Nangka', 'Oguis', 'Omanod',
      'Owak', 'Panalipan', 'Poblacion', 'San Vicente', 'Sandayong Norte',
      'Sandayong Sur', 'Santa Rosa', 'Santican', 'Sibacan', 'Suba',
      'Sulangan', 'Taboc', 'Taytay', 'Tuburan Norte', 'Tuburan Sur',
    ],
    Talisay: [
      'Biasong', 'Bulacao', 'Cadulawan', 'Campsig', 'Candulawan',
      'Cansojong', 'Dumlog', 'Jaclupan', 'Lagtang', 'Lawaan I',
      'Lawaan II', 'Lawaan III', 'Linao', 'Maghaway', 'Manipis',
      'Mohon', 'Naalad', 'Poblacion', 'Pooc', 'San Isidro',
      'San Jose', 'Tabunok', 'Tapul',
    ],
    Toledo: [
      'Awihao', 'Bagakay', 'Bato', 'Bunga', 'Cabitoonan',
      'Calongcalong', 'Cambang-ug', 'Camp 8', 'Canlumampao',
      'Cantabaco', 'Capitan Claudio', 'Carbon', 'Daanglungsod',
      'Don Andres Soriano', 'Dumlog', 'General Climaco', 'Ilihan',
      'Juan Climaco Sr.', 'Landahan', 'Loay', 'Luray II',
      'Media Once', 'Medina', 'Mgb', 'Poblacion', 'Poog',
      'Putingbato', 'Sam-ang', 'Sangi', 'Santo Niño', 'Sugarita',
      'Tubod', 'Tungkay',
    ],
    Naga: [
      'Alfaco', 'Bairan', 'Balirong', 'Cabungahan', 'Cantao-an',
      'Central Poblacion', 'Cogon', 'Colon', 'East Poblacion',
      'Inoburan', 'Inayagan', 'Inubog', 'Langtad', 'Lanas',
      'Lutac', 'Mainit', 'Mayana', 'Naalad', 'North Poblacion',
      'Ocana', 'Pangdan', 'Patag', 'Poblacion Central', 'San Agustin',
      'South Poblacion', 'Tagjaguimit', 'Tangke', 'Tinaan',
      'Tuyan', 'Uling', 'West Poblacion',
    ],
    Minglanilla: [
      'Cadulawan', 'Calajo-an', 'Camp 4', 'Cuanos', 'Guindaruhan',
      'Linao', 'Manduang', 'Pakigne', 'Poblacion Ward I',
      'Poblacion Ward II', 'Poblacion Ward III', 'Poblacion Ward IV',
      'Tubod', 'Tulay', 'Tungkop', 'Vito',
    ],
  },
  'Davao del Sur': {
    'Davao City': [
      'Agdao', 'Alambre', 'Alejandra Navarro', 'Alfonso Angliongto Sr.',
      'Angalan', 'Atan-Awe', 'Baganihan', 'Bago Aplaya', 'Bago Gallera',
      'Bago Oshiro', 'Baguio', 'Balengaeng', 'Baliok', 'Bangkas Heights',
      'Bantol', 'Baracatan', 'Biao Escuela', 'Biao Guianga', 'Biao Joaquin',
      'Binugao', 'Bucana', 'Buhangin Proper', 'Bunawan Proper',
      'Calinan Proper', 'Callawa', 'Catigan', 'Centro',
      'Communal', 'Crossing Bayabas', 'Dacudao', 'Dalag',
      'Daliaon Plantation', 'Datu Salumay', 'Dominga', 'Dumoy',
      'Eden', 'Fatima', 'Gatungan', 'Gov. Paciano Bangoy',
      'Gov. Vicente Duterte', 'Gumalang', 'Ilang', 'Inayangan',
      'Indangan', 'Kap. Tomas Monteverde Sr.', 'Lacson',
      'Lamanan', 'Lampianao', 'Lasang', 'Leon Garcia Sr.',
      'Lizada', 'Los Amigos', 'Lubogan', 'Lumiad', 'Ma-a',
      'Maa', 'Malagos', 'Malamba', 'Manambulan', 'Manuel Guianga',
      'Mapula', 'Marapangi', 'Marilog Proper', 'Matina Aplaya',
      'Matina Crossing', 'Matina Pangi', 'Mintal', 'Mudiang',
      'Mulig', 'New Carmen', 'New Valencia', 'Panacan',
      'Paquibato Proper', 'Paradise Embac', 'Riverside',
      'Sajahatra', 'Salaysay', 'Saloy', 'San Antonio',
      'San Isidro', 'Santos', 'Sasa', 'Sibulan',
      'Sirawan', 'Sirib', 'Suawan', 'Subasta', 'Sumimao',
      'Tacunan', 'Tagakpan', 'Talandang', 'Talomo Proper',
      'Tamayong', 'Tambobong', 'Tawan-Tawan', 'Tibuloy',
      'Tibungco', 'Tigatto', 'Toril Proper', 'Tugbok Proper',
      'Tungkalan', 'Ubalde', 'Ula', 'Waan', 'Wangan',
    ],
    Digos: [
      'Aplaya', 'Balabag', 'Binaton', 'Cogon', 'Colorado',
      'Dulangan', 'Goma', 'Igpit', 'Kapatagan', 'Kiagot',
      'Lungag', 'Mahayag', 'Matti', 'Meta', 'New Cebu',
      'New Visayas', 'Northgate', 'Paligue', 'Piao', 'Poblacion',
      'San Agustin', 'San Jose', 'San Miguel', 'San Pedro',
      'Sinawilan', 'Soong', 'Tiguman', 'Tres de Mayo',
    ],
    Mati: [
      'Central', 'Dahican', 'Dawan', 'Don Enrique Lopez',
      'Don Martin Marundan', 'Don Salvador Lopez Sr.',
      'Langka', 'Libudon', 'Luban', 'Macambol', 'Mamali',
      'Matiao', 'Mayo', 'Sainz', 'Sanghay', 'Tagabakid',
      'Tagbinonga', 'Taguibo', 'Tamisan',
    ],
    Panabo: [
      'Buenavista', 'Cacao', 'Cagangohan', 'Consolacion',
      'Dapco', 'Datu Abdul Dadia', 'Gredu', 'J.P. Laurel',
      'Kasilak', 'Katipunan', 'Kauswagan', 'Kawayanon',
      'Langkiwa', 'Lilo-an', 'Mabunao', 'Maduao', 'Malativas',
      'Manay', 'Nanyo', 'New Malaga', 'New Malitbog',
      'New Pandan', 'New Visayas', 'Quezon', 'Salvacion',
      'San Francisco', 'San Nicolas', 'San Pedro', 'San Roque',
      'San Vicente', 'Santa Cruz', 'Santo Niño', 'Sindaton',
      'Southern Davao', 'Tagtaguia', 'Talaingod', 'Tibungol',
      'Ula', 'Wangan',
    ],
    Tagum: [
      'Apokon', 'Bincungan', 'Busaon', 'Canocotan', 'Cuambogan',
      'La Filipina', 'Liboganon', 'Madaum', 'Magdum', 'Magugpo East',
      'Magugpo North', 'Magugpo Poblacion', 'Magugpo South', 'Magugpo West',
      'Mankilam', 'New Balamban', 'Nueva Fuerza', 'Pagsabangan',
      'Pandapan', 'San Agustin', 'San Isidro', 'San Miguel',
      'Visayan Village',
    ],
    Samal: [
      'Adecor', 'Anonang', 'Aumbay', 'Balet', 'Camudmud',
      'Del Monte', 'Guilon', 'Kanibungan', 'Kinawitnon', 'Libertad',
      'Limao', 'Linosutan', 'Mabago', 'Malinao', 'Miranda',
      'Omnibus', 'Peñaplata', 'Poblacion', 'Tambo', 'Toril',
    ],
    'Santo Tomas': [
      'Anonang', 'Arabaca', 'Balutakay', 'Binhibiranan',
      'Bongolanon', 'Buenavista', 'Cabuyagan', 'Cali',
      'Dalagdag', 'Darong', 'Dominorog', 'Dolo',
      'Goma', 'Jose Rizal', 'Kibongbong', 'Kimlawis',
      'Kinuskusan', 'Libertad', 'Luayon', 'Luna Norte',
      'Luna Sur', 'Lupon', 'Mabini', 'Magnaga', 'Maibo',
      'Malalag', 'Malasila', 'Malungon', 'New Bantay', 'New Bohol',
      'New Cebu', 'New Iloilo', 'New Leyte', 'New Visayas',
      'Nituan', 'Pag-asa', 'Pangian', 'Poblacion', 'Puyok',
      'Salaysay', 'Saub', 'Sinaragan', 'Sinawilan',
      'Tabayon', 'Tagolilong', 'Talao', 'Taocanga', 'Tawan-Tawan',
    ],
    Hagonoy: [
      'Dalawinon', 'Dalipawan', 'Harada Butai', 'Kibulan',
      'Kipalili', 'Kitaotao', 'Mabini', 'Manipongol', 'Matanao',
      'New Quezon', 'Paligue', 'Palma Gil', 'Poblacion', 'San Isidro',
      'San Roque',
    ],
    Malita: [
      'Bada', 'Balete', 'Balong', 'Buhangin', 'Culaman',
      'Don Aurelio Chicote', 'Kibalobalo', 'Mabini', 'Madidis',
      'Malatab', 'Manuel Peralta', 'New Argao', 'Pangaleon',
      'Poblacion', 'San Jose', 'Santa Maria', 'Talogoy',
      'Tim-baban', 'Tubalan',
    ],
    'Sta. Cruz': [
      'Asinan', 'Baranday', 'Bato', 'Bolila', 'Bulusan',
      'Datalbukay', 'Domolok', 'Glan Padidu', 'Guihing', 'Guihing Proper',
      'Kiblat', 'Lacaron', 'Langub', 'Lapulabao', 'Lasolon',
      'Linadasan', 'Mabini', 'Mabuhay', 'Malinawon', 'Matutungan',
      'Melitres', 'Paligue', 'Poblacion', 'Sangay', 'Tagulilag',
    ],
  },
  Iloilo: {
    'Iloilo City': [
      'Aduana', 'Aguinaldo', 'Aldeguer', 'Amambijon', 'Balabago',
      'Bo. Obrero', 'Bonifacio', 'Buenavista', 'Calumpang', 'City Proper',
      'Compania', 'Concepcion Ledesma', 'Consolacion', 'Danao',
      'East Baluarte', 'East Timawa', 'Edganzon', 'El 98 Riverside',
      'Fajardo', 'Flores', 'Habog-habog Salvacion', 'Hipodromo',
      'Inday', 'Jalandoni Estate', 'Jalandoni Pula', 'Kahirup', 'Kauswagan',
      'Lanit', 'La Paz', 'Lapuz Norte', 'Lapuz Sur',
      'Libertad', 'Magsaysay Village', 'Malipayon', 'Mansaya-Lapuz',
      'Mapa', 'Maria Clara', 'Mcarthur', 'Mission', 'Moroboro',
      'Navais', 'Obrero Carpenter', 'Obrero Lapuz', 'Ortiz',
      'Pale Benedicto Rizal', 'Pampango', 'Poblacion Molo', 'Progreso',
      'Quintin Salas', 'Rima-Rizal', 'Rizal Estanzuela', 'Rizal Ibarra',
      'Rizal Palapala I', 'Rizal Palapala II',
      'Sambag', 'San Agustin', 'San Alfonso', 'San Antonio',
      'San Enrique', 'San Isidro', 'San Jose', 'San Juan',
      'San Nicolas', 'San Pedro', 'Santa Filomena', 'Santo Niño Norte',
      'Santo Niño Sur', 'Santo Rosario', 'Seminario', 'Simon Ledesma',
      'Sooc', 'South Fundidor', 'Tanza-Buhay', 'Tanza-Burgos',
      'Tanza-Nuevo', 'Ticud', 'Timawa Tanza I', 'Timawa Tanza II',
      'Veterans Village', 'West Habog-Habog', 'Western Habog-Habog',
      'Yulo Drilon', 'Yulo King', 'Zone I Phhc Block', 'Zone II',
      'Zone III', 'Zone IV',
    ],
    Passi: [
      'Agdayao', 'Amamaros', 'Ayuyan', 'Ayuyan II', 'Bagacay',
      'Batu', 'Binangkalan', 'Bita', 'Buenavista', 'Bugtongan',
      'Cadimahan', 'Cag-an', 'Callan', 'Dalid', 'Dalocdoc',
      'Disiong', 'Dumolog', 'Durog', 'Gines', 'Guisian',
      'Imbang Grande', 'Imbang Pequeño', 'Ingwan', 'Intampilan',
      'Lalong', 'Maasin', 'Malonoy', 'Mambiranan Grande',
      'Mambiranan Pequeño', 'Man-it', 'Mantangon', 'Nasapian',
      'Palaclian', 'Pandan', 'Passi Proper', 'Pilapi', 'Poblacion',
      'Purog', 'Quipot', 'Samod', 'San Emilio', 'San Ivan',
      'San Jose', 'Sawa', 'Sebaste', 'Silagon', 'Tadi-an',
      'Talangnan', 'Talongonan', 'Tubungan', 'Tugaslon', 'Tumagboc',
    ],
    Oton: [
      'Aglonok', 'Alegre', 'Antonio Buendia Jr. Sr.', 'Atabayan',
      'Bita Norte', 'Bita Sur', 'Botong', 'Buayahon', 'Cabatuan',
      'Carriedo', 'Danao', 'Estanislao Villanueva', 'Francisca Baluyan',
      'Lindero', 'Lubog', 'Natividad Beluso', 'Natividad Chapantoc',
      'Pakiad', 'Pandan', 'Poblacion', 'Polo', 'Regador',
      'San Antonio', 'San Nicolas', 'San Vicente', 'Santa Cruz',
      'Santo Tomas', 'Santos Batula', 'Tagbac', 'Takway',
      'Tinocuan', 'Tugaslon', 'Tumagboc', 'Tumalintic',
    ],
    Pavia: [
      'Aganan', 'Amparo', 'Anilao', 'Balabag', 'Bragas',
      'Cabugao Norte', 'Cabugao Sur', 'Jibao-an', 'Mali-ao',
      'Paitan', 'Poblacion Norte', 'Poblacion Sur', 'Punong',
      'San Agustin Norte', 'San Agustin Sur', 'San Pedro',
      'Tacas', 'Tambak', 'Ungka I', 'Ungka II', 'Yubo',
    ],
    'Santa Barbara': [
      'Agboy Norte', 'Agboy Sur', 'Ag-ao', 'Amamaros',
      'Bagongon', 'Bagumbayan', 'Balabago', 'Balicuas',
      'Binolbog', 'Buyo', 'Cadoldolan', 'Cagmoanan',
      'Cansilayan', 'Doldol', 'Dugman', 'Enclaro',
      'Feliciano', 'Inawayan', 'Lanas', 'Lindero',
      'Linyer', 'Malinao', 'Mamhut Norte', 'Mamhut Sur',
      'Mina', 'Napnapan Norte', 'Napnapan Sur', 'Natividad',
      'Panginman', 'Patag', 'Poblacion', 'Potolan',
      'San Isidro', 'San Roque', 'Santa Maria', 'Sigue',
      'Supang', 'Talo-ato', 'Tigbauan', 'Tinaytay',
      'Tuburan', 'Tuguis',
    ],
    Cabatuan: [
      'Agdahon', 'Agusipan', 'Alimodias', 'Anandog', 'Ayaman',
      'Ayuyang', 'Bagacay', 'Baguingin-Lanot', 'Baguingin-Sugod',
      'Bangkal', 'Bantay', 'Belen', 'Bobon', 'Buyo',
      'Cabugao', 'Cadoldolan', 'Calaoagon', 'Cantalomboy',
      'Capalong', 'Capuluan', 'Cawayan', 'Corazon-Caingin',
      'Dangula-an', 'Dugo', 'Guinobatan', 'Indaluyon',
      'Janipa-an Este', 'Janipa-an Oeste', 'Inyawan', 'Lembak',
      'Linayuan', 'Lingsad', 'Lubog', 'Mabuligon',
      'Macatol', 'Magancina', 'Manaolan', 'Mandalagan',
      'Mariñas', 'Menan', 'Natividad', 'Ngalan',
      'Pandan', 'Patag-Abas', 'Poblacion', 'Poong',
      'Pungtod', 'Quinagtan', 'Sablogon', 'Salngan',
      'San Pedro', 'Sandayaw', 'Sapi-it', 'Siano',
      'Simbulan', 'Tampucao', 'Taoc', 'Tinaytay', 'Tuburan',
    ],
    Jaro: [
      'Balantang', 'Camalig', 'East Jaro', 'Fajardo', 'Lanit',
      'Magsaysay Village', 'Matag-ob', 'Navais', 'Pale Benedicto Rizal',
      'Pampango', 'Progreso', 'Quintin Salas', 'San Isidro',
      'San Jose', 'Santo Domingo', 'Taytay',
    ],
    Molo: [
      'Bangkerohan Ilawod', 'Bangkerohan Ilaya', 'Concepcion Ledesma',
      'Compania', 'Edganzon', 'Inday', 'Ortiz', 'San Enrique',
      'San Juan', 'Santo Niño Norte', 'Santo Niño Sur',
      'V. Corrales',
    ],
    Leon: [
      'Agboy', 'Alimodias', 'Balobalo', 'Balud-an', 'Bontoc',
      'Buenavista', 'Bulad', 'Bulong', 'Bumulao', 'Cagbuhangin',
      'Calalinan', 'Canas', 'Canturay', 'Gines Viejo',
      'Inabasan', 'Isolde', 'Itohan', 'Jalandoni',
      'Janipa-an', 'Lanas', 'Langca', 'Libo', 'Ligaya',
      'Lonoy', 'Lublub', 'Mabini', 'Malonoy',
      'Mambog', 'Mangil', 'Mansag', 'Maria Cristina',
      'Moroboro', 'Natividad', 'Olandes', 'Oton',
      'Pajo', 'Patag', 'Poblacion', 'Pungen', 'Quinagaringan',
      'Quinoblan', 'San Quintin', 'Singon', 'Sulangan',
      'Tabucan', 'Tibsoc', 'Tuburan',
    ],
    Tigbauan: [
      'Alupidian', 'Bacolod', 'Bacolod-Dacu', 'Bagongon',
      'Balantang', 'Barasan Este', 'Barasan Oeste', 'Baugbug',
      'Buenavista', 'Burot', 'Buyo', 'Cabilao',
      'Concordia Norte', 'Concordia Sur', 'Guisian',
      'Ilaud', 'Ille', 'Indag-an', 'Iyasan',
      'La Paz', 'Lawigan', 'Libo-on', 'Linao-an',
      'Loboc', 'Lugna', 'Mambog', 'Marigondon Norte',
      'Marigondon Sur', 'Navalas', 'Norala', 'Nublacion',
      'Pader Este', 'Pader Oeste', 'Panquian', 'Poblacion',
      'Polong Norte', 'Polong Sur', 'Sagondo',
      'San Fernando', 'San Jose', 'San Nicolas',
      'Serallo', 'Silagon', 'Sundong', 'Tamagoc',
      'Tibiao', 'Tigbauanon', 'Tiolas',
    ],
  },
  Pampanga: {
    'San Fernando': [
      'Alasas', 'Baliti', 'Bulaon', 'Calulut', 'Del Carmen',
      'Del Pilar', 'Del Rosario', 'Dolores', 'Juliana',
      'Lara', 'Lourdes', 'Maimpis', 'Malino', 'Malpitic',
      'Pandaras', 'Panipuan', 'Pulung Bulu', 'Quebiauan',
      'Saguin', 'San Agustin', 'San Felipe', 'San Isidro',
      'San Jose', 'San Juan', 'San Nicolas', 'San Pedro',
      'Santa Lucia', 'Santa Teresita', 'Santo Niño', 'Santo Rosario',
      'Sindalan', 'Telabastagan',
    ],
    Angeles: [
      'Agapito del Rosario', 'Amsic', 'Anunas', 'Balibago',
      'Capaya', 'Claro M. Recto', 'Cuayan', 'Cutcut',
      'Cutud', 'Lourdes Norte', 'Lourdes Sur', 'Lourdes Sur Este',
      'Malabanias', 'Margot', 'Mining', 'Ninoy Aquino',
      'Pampang', 'Pandan', 'Pulung Cacutud', 'Pulung Maragul',
      'Salapungan', 'San Jose', 'San Nicolas', 'San Pedro Cutud',
      'Santa Trinindad', 'Santo Cristo', 'Santo Domingo', 'Santo Rosario',
      'Sapangbato', 'Virgen delos Remedios',
    ],
    Mabalacat: [
      'Atlu-Bola', 'Bical', 'Bundagul', 'Cacutud', 'Calumpang',
      'Camachiles', 'Dapdap', 'Dau', 'Dolores', 'Duquit',
      'Lakandula', 'Mabiga', 'Macapagal', 'Mamatitang', 'Mangalit',
      'Marcos Village', 'Mawaque', 'Paralayunan', 'Poblacion',
      'San Francisco', 'San Joaquin', 'Santa Ines', 'Santa Maria',
      'Santo Rosario', 'Sapang Balen', 'Sapang Biabas', 'Tabun',
    ],
    Apalit: [
      'Balucuc', 'Calantipe', 'Cansinala', 'Capalangan',
      'Colgante', 'Paligui', 'Sampaloc', 'San Juan Baño',
      'San Vicente', 'Sucad', 'Sulipan', 'Tabuyuc',
    ],
    Lubao: [
      'Balantacan', 'Bancal Pugad', 'Bancal Sinubli', 'Baruya',
      'Calangain', 'Concepcion', 'Del Carmen', 'Don Ignacio Dimson',
      'Lourdes', 'Prado Siongco', 'Remedios', 'San Agustin',
      'San Antonio', 'San Isidro', 'San Jose Apunan', 'San Jose Gumi',
      'San Nicolas 1st', 'San Nicolas 2nd', 'San Pedro', 'San Ramon',
      'Santa Catalina', 'Santa Cruz', 'Santa Lucia', 'Santa Maria',
      'Santo Rosario', 'Sioce', 'Sto. Niño', 'Taguion',
    ],
    Porac: [
      'Babo Pangulo', 'Babo Sacan', 'Balubad', 'Bancal',
      'Camias', 'Cangatba', 'Diaz', 'Dolores', 'Jalung',
      'Mancatian', 'Manibaug Libutad', 'Manibaug Pasig', 'Manibaug Paralaya',
      'Manuali', 'Mitla Proper', 'Palat', 'Pias', 'Pio',
      'Planas', 'Poblacion', 'Pulung Santol', 'Salu', 'San Jose Mitla',
      'Santa Cruz', 'Sapang Uwak', 'Sepung Bulaon', 'Sinura',
      'Villa Maria',
    ],
    Guagua: [
      'Ascomo', 'Bancal', 'Jose Abad Santos', 'Lambac',
      'Maquiapo', 'Natividad', 'Pascual', 'Plea',
      'Pulungmasle', 'Rizal', 'San Agustin', 'San Antonio',
      'San Isidro', 'San Juan', 'San Matias', 'San Miguel',
      'San Pablo', 'San Pedro', 'San Rafael', 'San Roque',
      'San Vicente', 'Santiago', 'Santo Niño', 'Sta. Filomena',
    ],
    Macabebe: [
      'Batiakin', 'Caduang Tete', 'Candelaria', 'Castuli',
      'Consuelo', 'Dalayap', 'Lourdes', 'Lupac', 'Malinta',
      'Minalin', 'Palanas', 'Poblacion', 'San Agustin',
      'San Esteban', 'San Francisco', 'San Gabriel',
      'San Isidro', 'San Jose', 'San Juan', 'San Nicolas',
      'San Pablo', 'San Rafael', 'San Roque', 'San Simplicio',
      'San Vicente', 'Santa Cruz', 'Santa Lutgarda', 'Santa Maria',
      'Santa Rufina', 'Santo Niño', 'Saplad David', 'Tacasan',
      'Valdez',
    ],
    Magalang: [
      'Alag', 'Bucanan', 'Camias', 'Dolores', 'Escaler',
      'La Paz', 'Navaling', 'San Agustin', 'San Antonio',
      'San Francisco', 'San Ildefonso', 'San Isidro', 'San Jose',
      'San Pedro', 'San Vicente', 'Santa Cruz', 'Santa Lucia',
      'Santa Maria', 'Santo Niño', 'Santo Rosario', 'Turu',
    ],
    Mexico: [
      'Acli', 'Anao', 'Balas', 'Belen', 'Brgy. I',
      'Brgy. II', 'Brgy. III', 'Brgy. IV', 'Brgy. V',
      'Brgy. VI', 'Brgy. VII', 'Brgy. VIII', 'Brgy. IX',
      'Brgy. X', 'Brgy. XI', 'Brgy. XII', 'Brgy. XIII',
      'Brgy. XIV', 'Brgy. XV', 'Brgy. XVI', 'Brgy. XVII',
      'Brgy. XVIII', 'Brgy. XIX', 'Brgy. XX',
      'Burnay', 'Camuning', 'Cawayan Bugtong', 'Concepcion',
      'Culubasa', 'Dela Paz', 'Dolores', 'Eden', 'Laput',
      'Laug', 'Masamat', 'Masangsang', 'Nueva Victoria',
      'Pandacaqui', 'Pangatlan', 'Panipuan', 'Parian',
      'Poblacion', 'Pulong Maragul', 'Sabanilla', 'San Antonio',
      'San Carlos', 'San Jose Malino', 'San Jose Matulid',
      'San Juan', 'San Lorenzo', 'San Miguel', 'San Nicolas',
      'San Pablo', 'San Patricio', 'San Rafael', 'San Roque',
      'San Vicente', 'Santa Cruz', 'Santa Maria', 'Santo Niño',
      'Santo Tomas', 'Sapang Maisac', 'Suclaban', 'Tangle',
    ],
  },
  Batangas: {
    'Batangas City': [
      'Alagao', 'Aplaya', 'Balagtas', 'Balete', 'Banaba Center',
      'Banaba Kanluran', 'Banaba Silangan', 'Banaba Ibaba',
      'Barangay 1', 'Barangay 2', 'Barangay 3', 'Barangay 4',
      'Barangay 5', 'Barangay 6', 'Barangay 7', 'Barangay 8',
      'Barangay 9', 'Barangay 10', 'Barangay 11', 'Barangay 12',
      'Barangay 13', 'Barangay 14', 'Barangay 15', 'Barangay 16',
      'Barangay 17', 'Barangay 18', 'Barangay 19', 'Barangay 20',
      'Barangay 21', 'Barangay 22', 'Barangay 23', 'Barangay 24',
      'Bolbok', 'Bungahan', 'Calicanto', 'Cuta', 'Dela Paz',
      'Dumantay', 'Gulod Itaas', 'Gulod Labac', 'Haligue Kanluran',
      'Haligue Silangan', 'Ilihan', 'Kumintang Ibaba', 'Kumintang Ilaya',
      'Libjo', 'Liponpon', 'Maapaz', 'Mabacong', 'Mahabang Parang',
      'Mahacot Kanluran', 'Mahacot Silangan', 'Malanday', 'Maruclap',
      'Palahanan I', 'Palahanan II', 'Pamilhan', 'Paringao',
      'Pinamucan Ibaba', 'Pinamucan Proper', 'Pinamucan Silangan',
      'Poblacion', 'Sampaga', 'San Agapito', 'San Agustin Kanluran',
      'San Agustin Silangan', 'San Andres', 'San Antonio',
      'San Isidro', 'San Jose Sico', 'San Miguel', 'Santa Clara',
      'Santa Rita Aplaya', 'Santa Rita Karsada', 'Simlong', 'Sorosoro Ibaba',
      'Sorosoro Ilaya', 'Sorosoro Karsada', 'Tabangao-Ambulong',
      'Tabangao-Aplaya', 'Tabangao-Dao', 'Talahib Pandayan',
      'Talahib Payapa', 'Talumpok Kanluran', 'Talumpok Silangan',
      'Tinga Itaas', 'Tinga Labac', 'Tingga Itaas', 'Tingga Labac',
      'Wawa',
    ],
    Lipa: [
      'Adya', 'Anilao-Labac', 'Antipolo del Norte', 'Antipolo del Sur',
      'Bagong Pook', 'Balintawak', 'Banaybanay', 'Banjo East',
      'Banjo West', 'Bañadero', 'Bolbok', 'Buhay na Tubig',
      'Bulaklak', 'Bulacan', 'Calamias', 'Cumba', 'Dagatan',
      'Duhatan', 'Guinhawa Norte', 'Guinhawa Sur', 'Inosluban',
      'Kayumanggi', 'Latag', 'Lodlod', 'Lumbang', 'Mabini',
      'Mabini Ibaba', 'Malagonlong', 'Malitlit', 'Marauoy',
      'Mataas na Lupa', 'Munting Pulo', 'Pagolingin Bata',
      'Pagolingin East', 'Pagolingin West', 'Pangao', 'Pinagkawitan',
      'Pinagtongulan', 'Plaridel', 'Poblacion Barangay 1',
      'Poblacion Barangay 2', 'Poblacion Barangay 3', 'Poblacion Barangay 4',
      'Poblacion Barangay 5', 'Poblacion Barangay 6', 'Poblacion Barangay 7',
      'Poblacion Barangay 8', 'Poblacion Barangay 9', 'Poblacion Barangay 10',
      'Poblacion Barangay 11', 'Poblacion Barangay 12',
      'Pusil', 'Quezon', 'Rizal', 'Sabang', 'Sampaguita',
      'San Benito', 'San Carlos', 'San Celestino', 'San Francisco',
      'San Guillermo', 'San Jose', 'San Lucas', 'San Salvador',
      'San Sebastian', 'Sandia', 'Santa Cruz', 'Santo Niño',
      'Santo Toribio', 'Sico', 'Sigad', 'Tibig', 'Tipacan',
    ],
    Tanauan: [
      'Altura Bata', 'Altura Matanda', 'Anus', 'Apacay',
      'Bañadero', 'Baolaney', 'Bilog-Bilog', 'Boot',
      'Cale', 'Darasa', 'Gonzales', 'Hidalgo',
      'Kay-Anlog', 'Luta del Norte', 'Luta del Sur',
      'Mahabang Parang', 'Mataas na Lupa', 'Natatas',
      'Pagaspas', 'Pantay Matanda', 'Pantay Bata',
      'Poblacion Barangay 1', 'Poblacion Barangay 2', 'Poblacion Barangay 3',
      'Poblacion Barangay 4', 'Poblacion Barangay 5', 'Poblacion Barangay 6',
      'Sala', 'Sambat', 'San Jose', 'Santor', 'Sulpoc',
      'Suplang', 'Talaga', 'Tinurik', 'Trapiche', 'Ulango', 'Wawa',
    ],
    Bauan: [
      'Alagao', 'Aplaya', 'As-Is', 'Bagong Pook', 'Balayong',
      'Barangay I', 'Barangay II', 'Barangay III', 'Barangay IV',
      'Barangay V', 'Barangay VI', 'Barangay VII', 'Barangay VIII',
      'Bilog-Bilog', 'Cahigam', 'Calumpang Kanluran', 'Calumpang Silangan',
      'Catandaan', 'Cumba', 'Durungao', 'Gulod', 'Lagnas',
      'Lanatan', 'Libtong', 'Lipahan', 'Maaibon', 'Magahis',
      'Malindig', 'Malusak', 'Manghinao Proper', 'Manghinao Uno',
      'Matoco', 'Munting Mulo', 'Nagtalongtong', 'Navotas',
      'Pitugo', 'Rizal', 'San Miguel', 'Sampaga',
      'Santa Presa', 'Sinala', 'Solo', 'Talahib',
    ],
    'Santo Tomas': [
      'Barangay I', 'Barangay II', 'Barangay III', 'Barangay IV',
      'Barangay V', 'Barangay VI', 'Barangay VII', 'Barangay VIII',
      'Barangay IX', 'Barangay X', 'Barangay XI', 'Barangay XII',
      'Barangay XIII', 'Barangay XIV', 'Barangay XV',
      'Barangay XVI', 'Barangay XVII', 'Barangay XVIII',
      'Barangay XIX', 'Barangay XX', 'Barangay XXI',
      'Barangay XXII', 'Barangay XXIII',
    ],
    Nasugbu: [
      'Aga', 'Balaytigui', 'Banilad', 'Bilaran', 'Bucana',
      'Bulihan', 'Bunducan', 'Butucan', 'Calayo', 'Catandaan',
      'Cogunan', 'Dayapan', 'Kaylaway', 'Kayrilaw', 'Lumbangan',
      'Maugat East', 'Maugat West', 'Munting Indan', 'Natipuan',
      'Pantalan', 'Papaya', 'Poblacion I', 'Poblacion II',
      'Poblacion III', 'Poblacion IV', 'Poblacion V',
      'Populated', 'Reparo', 'Salaban', 'Talangan',
      'Tumalim', 'Utod', 'Wawa',
    ],
    Balayan: [
      'Baclaran', 'Bagong Pook', 'Bignay I', 'Bignay II',
      'Bolaney', 'Bolo', 'Caloocan', 'Calzada', 'Canda',
      'Colocabo', 'Culading', 'Dao', 'Dilao', 'Duhatan',
      'Durungao', 'Gimalas', 'Gumamela', 'Lagnas',
      'Lumbangan', 'Mabini', 'Maliksi', 'Malsol', 'Mango',
      'Mansalaya', 'Nagalang', 'Pagkilatan', 'Palikpikan',
      'Parang', 'Pinaglikuan', 'Poblacion', 'Quilo-quilo',
      'Quinale', 'Salong', 'San Juan', 'Santo Niño',
      'Sukol', 'Tactac', 'Taludtod', 'Tanggoy',
    ],
    Lemery: [
      'Alabado', 'Alapan', 'Amuyong', 'Apacay', 'Bukal',
      'Bulbulan', 'Bulihan', 'Calumpang', 'Cuta', 'Dagatan',
      'Halang', 'Hipit', 'Ilog Tubig', 'Imelda', 'Lagnas',
      'Mabini', 'Malapad na Bato', 'Malapad na Parang',
      'Malinao', 'Marilag', 'Masaguitsit', 'Navotas',
      'Palsahingin', 'Pangao', 'Pinagalapan', 'Pook',
      'Poblacion Ilaya', 'Poblacion Ibaba', 'Pulang Lupa',
      'Rizal', 'Sampalukan', 'San Isidro', 'San Roque',
      'Santa Maria', 'Santo Niño', 'Sapac', 'Sico I',
      'Sico II', 'Suntal', 'Talisay', 'Tanuan',
      'Taysan', 'Tingloy', 'Tuy',
    ],
    Rosario: [
      'Alupay', 'Ambulong', 'Banaba', 'Banaybanay', 'Biga',
      'Calo', 'Caloocan', 'Dahican', 'Dao', 'Dingin',
      'Duhatan', 'Kaulayanan', 'Latag', 'Loок', 'Mabunga',
      'Maigsing Dahilig', 'Malindig', 'Malipuyon', 'Malpitic',
      'Mapulo', 'Maruclap', 'Matamis', 'Munting Tubig',
      'Nagsaulay', 'Nagtalongtong', 'Paligbrakan', 'Panghayaan',
      'Pansipit', 'Pinalunan', 'Pinangkawitan', 'Pinagtibukan',
      'Pook', 'Poblacion', 'Sabang', 'Sampaga', 'San Agustin',
      'San Antonio', 'San Francisco', 'San Roque', 'Santa Cruz',
      'Santo Tomas', 'Talaga', 'Tamak', 'Tinurik',
    ],
    'San Jose': [
      'Abelo', 'Aguila', 'Alagao', 'Ampel', 'Bago',
      'Bagong Pook', 'Balibago', 'Balimbing', 'Bukal',
      'Bulihan', 'Caloocan', 'Dalig', 'Dao', 'Duhat',
      'Halang', 'Imelda', 'Ipil', 'Lagnas', 'Lumbangan',
      'Mabini', 'Malapad na Bato', 'Malinao', 'Manguisian',
      'Marilag', 'Narra', 'Poblacion', 'Pulo', 'Sampaga',
      'San Isidro', 'San Miguel', 'Santa Cruz', 'Santo Niño',
      'Sapac', 'Talahib', 'Taysan', 'Tubigan', 'Wawa',
    ],
  },
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const type = searchParams.get('type')

  if (type === 'provinces') {
    return NextResponse.json({ provinces: provinces.map((p) => p.name) })
  }

  if (type === 'municipalities') {
    const province = searchParams.get('province')
    const provinceData = provinces.find((p) => p.name === province)
    if (!provinceData) {
      return NextResponse.json({ error: 'Province not found' }, { status: 404 })
    }
    return NextResponse.json({ municipalities: provinceData.municipalities })
  }

  if (type === 'barangays') {
    const province = searchParams.get('province')
    const municipality = searchParams.get('municipality')
    if (!province || !municipality) {
      return NextResponse.json({ barangays: [] })
    }
    const barangays = barangayData[province]?.[municipality] ?? []
    return NextResponse.json({ barangays })
  }

  return NextResponse.json({ error: 'Invalid type parameter' }, { status: 400 })
}
